name: Test

on: 
  repository_dispatch:
  workflow_dispatch:
    inputs:
      start_test:
        required: false
        default: '1'

jobs:
  test:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Test
      shell: bash
      run: ./test.sh
